# Generated by Django 3.1.4 on 2022-06-25 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted'], 'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
